import { useState } from "react";
import { useQuery, useQueryClient } from "@tanstack/react-query";
import { supabase } from "@/integrations/supabase/client";
import { Card } from "@/components/AppShell";

export function AgentAdmin() {
  const [prompt, setPrompt] = useState("");
  const [selected, setSelected] = useState<any | null>(null);
  const qc = useQueryClient();
  const prompts = useQuery({ queryKey: ["agent-prompts"], queryFn: async () => (await supabase.from("agent_prompts").select("*").order("created_at", { ascending: false })).data ?? [] });
  const conversations = useQuery({ queryKey: ["agent-all-conversations"], queryFn: async () => (await supabase.from("ai_conversations").select("*").order("updated_at", { ascending: false }).limit(300)).data ?? [] });
  const profiles = useQuery({ queryKey: ["agent-audit-profiles"], queryFn: async () => (await supabase.from("profiles").select("id,full_name,student_id")).data ?? [] });
  const profileById = new Map((profiles.data ?? []).map((profile: any) => [profile.id, profile]));
  const addPrompt = async () => { if (!prompt.trim()) return; await supabase.from("agent_prompts").insert({ prompt: prompt.trim(), created_by: (await supabase.auth.getUser()).data.user?.id }); setPrompt(""); qc.invalidateQueries({ queryKey: ["agent-prompts"] }); };
  const deletePrompt = async (id: string) => { await supabase.from("agent_prompts").update({ is_active: false }).eq("id", id); qc.invalidateQueries({ queryKey: ["agent-prompts"] }); };
  const loadMessages = async (conversation: any) => { const { data } = await supabase.from("ai_conversation_messages").select("role,content,created_at").eq("conversation_id", conversation.id).order("created_at"); setSelected({ ...conversation, messages: data ?? [] }); };
  const hardDelete = async (id: string) => { if (!window.confirm("حذف نهائي؟ لا يمكن التراجع.")) return; await fetch(`/api/ai/admin?conversationId=${id}`, { method: "DELETE", headers: { Authorization: `Bearer ${(await supabase.auth.getSession()).data.session?.access_token ?? ""}` } }); setSelected(null); qc.invalidateQueries({ queryKey: ["agent-all-conversations"] }); };
  return <div className="space-y-5" dir="rtl"><Card><div className="font-bold mb-2">تعليمات الوكيل</div><div className="text-xs text-muted-foreground mb-3">تُطبّق التعليمات النشطة على خطط عبوسي الجديدة، مثل منعه من حل الواجبات.</div><div className="flex gap-2"><input value={prompt} onChange={(e) => setPrompt(e.target.value)} className="flex-1 glass rounded-xl p-3 text-sm" placeholder="اكتب تعليمات جديدة للوكيل" /><button onClick={() => void addPrompt()} className="rounded-xl bg-accent text-accent-foreground px-4 text-sm font-bold">إضافة</button></div><div className="space-y-2 mt-4">{prompts.data?.map((item: any) => <div key={item.id} className={`glass rounded-xl p-3 text-sm flex justify-between gap-3 ${!item.is_active ? "opacity-50" : ""}`}><span>{item.prompt}</span>{item.is_active && <button onClick={() => void deletePrompt(item.id)} className="text-destructive text-xs">تعطيل</button>}</div>)}</div></Card><Card><div className="font-bold mb-3">سجل محادثات الطلاب</div><div className="text-xs text-muted-foreground mb-3">يمكنك القراءة والتدقيق فقط. لا يمكن للمالك المراسلة من حساب الطالب أو تعديل اسم المحادثة.</div><div className="space-y-2 max-h-[500px] overflow-auto">{conversations.data?.map((conversation: any) => { const profile = profileById.get(conversation.user_id) as any; return <button key={conversation.id} onClick={() => void loadMessages(conversation)} className="w-full text-right glass rounded-xl p-3"><div className="font-bold text-sm">{conversation.title}</div><div className="text-[10px] text-muted-foreground">الطالب: {profile?.full_name ?? conversation.user_id}{profile?.student_id ? ` (${profile.student_id})` : ""} {conversation.user_deleted_at ? "• محذوفة من الطالب" : ""}</div></button>; })}</div></Card>{selected && <Card><div className="flex justify-between items-center mb-3"><b>{selected.title}</b><button onClick={() => void hardDelete(selected.id)} className="text-xs text-destructive">حذف نهائي</button></div><div className="space-y-2 max-h-[450px] overflow-auto">{selected.messages.map((message: any, index: number) => <div key={index} className="glass rounded-xl p-3 text-sm"><b>{message.role === "user" ? "الطالب" : "عبوسي"}</b><div className="whitespace-pre-wrap mt-1">{message.content}</div></div>)}</div></Card>}</div>;
}
