/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AiRouteImport } from './routes/ai'
import { Route as AnnouncementsRouteImport } from './routes/announcements'
import { Route as BooksRouteImport } from './routes/books'
import { Route as CalendarRouteImport } from './routes/calendar'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as EventsRouteImport } from './routes/events'
import { Route as ExamsRouteImport } from './routes/exams'
import { Route as GradesRouteImport } from './routes/grades'
import { Route as GroupsRouteImport } from './routes/groups'
import { Route as HomeworkRouteImport } from './routes/homework'
import { Route as LoginRouteImport } from './routes/login'
import { Route as MessagesRouteImport } from './routes/messages'
import { Route as NewsRouteImport } from './routes/news'
import { Route as PrivacyPolicyRouteImport } from './routes/privacy-policy'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as ScheduleRouteImport } from './routes/schedule'
import { Route as SearchRouteImport } from './routes/search'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as TeachersRouteImport } from './routes/teachers'
import { Route as ToolsRouteImport } from './routes/tools'
import { Route as VideosRouteImport } from './routes/videos'
import { Route as ApiAgentRouteImport } from './routes/api/agent'
import { Route as ApiChatRouteImport } from './routes/api/chat'
import { Route as ApiGradeTextRouteImport } from './routes/api/grade-text'
import { Route as ApiRemindersRouteImport } from './routes/api/reminders'
import { Route as DmUserIdRouteImport } from './routes/dm.$userId'
import { Route as ExamsQuizIdRouteImport } from './routes/exams.$quizId'
import { Route as GroupsIndexRouteImport } from './routes/groups.index'
import { Route as GroupsGroupIdRouteImport } from './routes/groups.$groupId'
import { Route as ApiAiActionsRouteImport } from './routes/api/ai/actions'
import { Route as ApiAiAdminRouteImport } from './routes/api/ai/admin'
import { Route as ApiAiConversationsRouteImport } from './routes/api/ai/conversations'
import { Route as ApiAiReportRouteImport } from './routes/api/ai/report'
import { Route as ApiAiVisionRouteImport } from './routes/api/ai/vision'
import { Route as ApiBooksIndexRouteImport } from './routes/api/books/index'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AiRoute = AiRouteImport.update({
  id: '/ai',
  path: '/ai',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/ai.lazy').then((d) => d.Route))
const AnnouncementsRoute = AnnouncementsRouteImport.update({
  id: '/announcements',
  path: '/announcements',
  getParentRoute: () => rootRouteImport,
} as any)
const BooksRoute = BooksRouteImport.update({
  id: '/books',
  path: '/books',
  getParentRoute: () => rootRouteImport,
} as any)
const CalendarRoute = CalendarRouteImport.update({
  id: '/calendar',
  path: '/calendar',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const EventsRoute = EventsRouteImport.update({
  id: '/events',
  path: '/events',
  getParentRoute: () => rootRouteImport,
} as any)
const ExamsRoute = ExamsRouteImport.update({
  id: '/exams',
  path: '/exams',
  getParentRoute: () => rootRouteImport,
} as any)
const GradesRoute = GradesRouteImport.update({
  id: '/grades',
  path: '/grades',
  getParentRoute: () => rootRouteImport,
} as any)
const GroupsRoute = GroupsRouteImport.update({
  id: '/groups',
  path: '/groups',
  getParentRoute: () => rootRouteImport,
} as any)
const HomeworkRoute = HomeworkRouteImport.update({
  id: '/homework',
  path: '/homework',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const MessagesRoute = MessagesRouteImport.update({
  id: '/messages',
  path: '/messages',
  getParentRoute: () => rootRouteImport,
} as any)
const NewsRoute = NewsRouteImport.update({
  id: '/news',
  path: '/news',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyPolicyRoute = PrivacyPolicyRouteImport.update({
  id: '/privacy-policy',
  path: '/privacy-policy',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const ScheduleRoute = ScheduleRouteImport.update({
  id: '/schedule',
  path: '/schedule',
  getParentRoute: () => rootRouteImport,
} as any)
const SearchRoute = SearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const TeachersRoute = TeachersRouteImport.update({
  id: '/teachers',
  path: '/teachers',
  getParentRoute: () => rootRouteImport,
} as any)
const ToolsRoute = ToolsRouteImport.update({
  id: '/tools',
  path: '/tools',
  getParentRoute: () => rootRouteImport,
} as any)
const VideosRoute = VideosRouteImport.update({
  id: '/videos',
  path: '/videos',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAgentRoute = ApiAgentRouteImport.update({
  id: '/api/agent',
  path: '/api/agent',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiChatRoute = ApiChatRouteImport.update({
  id: '/api/chat',
  path: '/api/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiGradeTextRoute = ApiGradeTextRouteImport.update({
  id: '/api/grade-text',
  path: '/api/grade-text',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiRemindersRoute = ApiRemindersRouteImport.update({
  id: '/api/reminders',
  path: '/api/reminders',
  getParentRoute: () => rootRouteImport,
} as any)
const DmUserIdRoute = DmUserIdRouteImport.update({
  id: '/dm/$userId',
  path: '/dm/$userId',
  getParentRoute: () => rootRouteImport,
} as any)
const ExamsQuizIdRoute = ExamsQuizIdRouteImport.update({
  id: '/$quizId',
  path: '/$quizId',
  getParentRoute: () => ExamsRoute,
} as any)
const GroupsIndexRoute = GroupsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => GroupsRoute,
} as any)
const GroupsGroupIdRoute = GroupsGroupIdRouteImport.update({
  id: '/$groupId',
  path: '/$groupId',
  getParentRoute: () => GroupsRoute,
} as any)
const ApiAiActionsRoute = ApiAiActionsRouteImport.update({
  id: '/api/ai/actions',
  path: '/api/ai/actions',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAiAdminRoute = ApiAiAdminRouteImport.update({
  id: '/api/ai/admin',
  path: '/api/ai/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAiConversationsRoute = ApiAiConversationsRouteImport.update({
  id: '/api/ai/conversations',
  path: '/api/ai/conversations',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAiReportRoute = ApiAiReportRouteImport.update({
  id: '/api/ai/report',
  path: '/api/ai/report',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAiVisionRoute = ApiAiVisionRouteImport.update({
  id: '/api/ai/vision',
  path: '/api/ai/vision',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiBooksIndexRoute = ApiBooksIndexRouteImport.update({
  id: '/api/books/',
  path: '/api/books/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/ai': typeof AiRoute
  '/announcements': typeof AnnouncementsRoute
  '/books': typeof BooksRoute
  '/calendar': typeof CalendarRoute
  '/contact': typeof ContactRoute
  '/events': typeof EventsRoute
  '/exams': typeof ExamsRouteWithChildren
  '/grades': typeof GradesRoute
  '/groups': typeof GroupsRouteWithChildren
  '/homework': typeof HomeworkRoute
  '/login': typeof LoginRoute
  '/messages': typeof MessagesRoute
  '/news': typeof NewsRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/profile': typeof ProfileRoute
  '/schedule': typeof ScheduleRoute
  '/search': typeof SearchRoute
  '/settings': typeof SettingsRoute
  '/teachers': typeof TeachersRoute
  '/tools': typeof ToolsRoute
  '/videos': typeof VideosRoute
  '/api/agent': typeof ApiAgentRoute
  '/api/chat': typeof ApiChatRoute
  '/api/grade-text': typeof ApiGradeTextRoute
  '/api/reminders': typeof ApiRemindersRoute
  '/dm/$userId': typeof DmUserIdRoute
  '/exams/$quizId': typeof ExamsQuizIdRoute
  '/groups/$groupId': typeof GroupsGroupIdRoute
  '/groups/': typeof GroupsIndexRoute
  '/api/ai/actions': typeof ApiAiActionsRoute
  '/api/ai/admin': typeof ApiAiAdminRoute
  '/api/ai/conversations': typeof ApiAiConversationsRoute
  '/api/ai/report': typeof ApiAiReportRoute
  '/api/ai/vision': typeof ApiAiVisionRoute
  '/api/books/': typeof ApiBooksIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/ai': typeof AiRoute
  '/announcements': typeof AnnouncementsRoute
  '/books': typeof BooksRoute
  '/calendar': typeof CalendarRoute
  '/contact': typeof ContactRoute
  '/events': typeof EventsRoute
  '/exams': typeof ExamsRouteWithChildren
  '/grades': typeof GradesRoute
  '/homework': typeof HomeworkRoute
  '/login': typeof LoginRoute
  '/messages': typeof MessagesRoute
  '/news': typeof NewsRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/profile': typeof ProfileRoute
  '/schedule': typeof ScheduleRoute
  '/search': typeof SearchRoute
  '/settings': typeof SettingsRoute
  '/teachers': typeof TeachersRoute
  '/tools': typeof ToolsRoute
  '/videos': typeof VideosRoute
  '/api/agent': typeof ApiAgentRoute
  '/api/chat': typeof ApiChatRoute
  '/api/grade-text': typeof ApiGradeTextRoute
  '/api/reminders': typeof ApiRemindersRoute
  '/dm/$userId': typeof DmUserIdRoute
  '/exams/$quizId': typeof ExamsQuizIdRoute
  '/groups/$groupId': typeof GroupsGroupIdRoute
  '/groups': typeof GroupsIndexRoute
  '/api/ai/actions': typeof ApiAiActionsRoute
  '/api/ai/admin': typeof ApiAiAdminRoute
  '/api/ai/conversations': typeof ApiAiConversationsRoute
  '/api/ai/report': typeof ApiAiReportRoute
  '/api/ai/vision': typeof ApiAiVisionRoute
  '/api/books': typeof ApiBooksIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/ai': typeof AiRoute
  '/announcements': typeof AnnouncementsRoute
  '/books': typeof BooksRoute
  '/calendar': typeof CalendarRoute
  '/contact': typeof ContactRoute
  '/events': typeof EventsRoute
  '/exams': typeof ExamsRouteWithChildren
  '/grades': typeof GradesRoute
  '/groups': typeof GroupsRouteWithChildren
  '/homework': typeof HomeworkRoute
  '/login': typeof LoginRoute
  '/messages': typeof MessagesRoute
  '/news': typeof NewsRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/profile': typeof ProfileRoute
  '/schedule': typeof ScheduleRoute
  '/search': typeof SearchRoute
  '/settings': typeof SettingsRoute
  '/teachers': typeof TeachersRoute
  '/tools': typeof ToolsRoute
  '/videos': typeof VideosRoute
  '/api/agent': typeof ApiAgentRoute
  '/api/chat': typeof ApiChatRoute
  '/api/grade-text': typeof ApiGradeTextRoute
  '/api/reminders': typeof ApiRemindersRoute
  '/dm/$userId': typeof DmUserIdRoute
  '/exams/$quizId': typeof ExamsQuizIdRoute
  '/groups/$groupId': typeof GroupsGroupIdRoute
  '/groups/': typeof GroupsIndexRoute
  '/api/ai/actions': typeof ApiAiActionsRoute
  '/api/ai/admin': typeof ApiAiAdminRoute
  '/api/ai/conversations': typeof ApiAiConversationsRoute
  '/api/ai/report': typeof ApiAiReportRoute
  '/api/ai/vision': typeof ApiAiVisionRoute
  '/api/books/': typeof ApiBooksIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/ai'
    | '/announcements'
    | '/books'
    | '/calendar'
    | '/contact'
    | '/events'
    | '/exams'
    | '/grades'
    | '/groups'
    | '/homework'
    | '/login'
    | '/messages'
    | '/news'
    | '/privacy-policy'
    | '/profile'
    | '/schedule'
    | '/search'
    | '/settings'
    | '/teachers'
    | '/tools'
    | '/videos'
    | '/api/agent'
    | '/api/chat'
    | '/api/grade-text'
    | '/api/reminders'
    | '/dm/$userId'
    | '/exams/$quizId'
    | '/groups/$groupId'
    | '/groups/'
    | '/api/ai/actions'
    | '/api/ai/admin'
    | '/api/ai/conversations'
    | '/api/ai/report'
    | '/api/ai/vision'
    | '/api/books/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/ai'
    | '/announcements'
    | '/books'
    | '/calendar'
    | '/contact'
    | '/events'
    | '/exams'
    | '/grades'
    | '/homework'
    | '/login'
    | '/messages'
    | '/news'
    | '/privacy-policy'
    | '/profile'
    | '/schedule'
    | '/search'
    | '/settings'
    | '/teachers'
    | '/tools'
    | '/videos'
    | '/api/agent'
    | '/api/chat'
    | '/api/grade-text'
    | '/api/reminders'
    | '/dm/$userId'
    | '/exams/$quizId'
    | '/groups/$groupId'
    | '/groups'
    | '/api/ai/actions'
    | '/api/ai/admin'
    | '/api/ai/conversations'
    | '/api/ai/report'
    | '/api/ai/vision'
    | '/api/books'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/ai'
    | '/announcements'
    | '/books'
    | '/calendar'
    | '/contact'
    | '/events'
    | '/exams'
    | '/grades'
    | '/groups'
    | '/homework'
    | '/login'
    | '/messages'
    | '/news'
    | '/privacy-policy'
    | '/profile'
    | '/schedule'
    | '/search'
    | '/settings'
    | '/teachers'
    | '/tools'
    | '/videos'
    | '/api/agent'
    | '/api/chat'
    | '/api/grade-text'
    | '/api/reminders'
    | '/dm/$userId'
    | '/exams/$quizId'
    | '/groups/$groupId'
    | '/groups/'
    | '/api/ai/actions'
    | '/api/ai/admin'
    | '/api/ai/conversations'
    | '/api/ai/report'
    | '/api/ai/vision'
    | '/api/books/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  AiRoute: typeof AiRoute
  AnnouncementsRoute: typeof AnnouncementsRoute
  BooksRoute: typeof BooksRoute
  CalendarRoute: typeof CalendarRoute
  ContactRoute: typeof ContactRoute
  EventsRoute: typeof EventsRoute
  ExamsRoute: typeof ExamsRouteWithChildren
  GradesRoute: typeof GradesRoute
  GroupsRoute: typeof GroupsRouteWithChildren
  HomeworkRoute: typeof HomeworkRoute
  LoginRoute: typeof LoginRoute
  MessagesRoute: typeof MessagesRoute
  NewsRoute: typeof NewsRoute
  PrivacyPolicyRoute: typeof PrivacyPolicyRoute
  ProfileRoute: typeof ProfileRoute
  ScheduleRoute: typeof ScheduleRoute
  SearchRoute: typeof SearchRoute
  SettingsRoute: typeof SettingsRoute
  TeachersRoute: typeof TeachersRoute
  ToolsRoute: typeof ToolsRoute
  VideosRoute: typeof VideosRoute
  ApiAgentRoute: typeof ApiAgentRoute
  ApiChatRoute: typeof ApiChatRoute
  ApiGradeTextRoute: typeof ApiGradeTextRoute
  ApiRemindersRoute: typeof ApiRemindersRoute
  DmUserIdRoute: typeof DmUserIdRoute
  ApiAiActionsRoute: typeof ApiAiActionsRoute
  ApiAiAdminRoute: typeof ApiAiAdminRoute
  ApiAiConversationsRoute: typeof ApiAiConversationsRoute
  ApiAiReportRoute: typeof ApiAiReportRoute
  ApiAiVisionRoute: typeof ApiAiVisionRoute
  ApiBooksIndexRoute: typeof ApiBooksIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ai': {
      id: '/ai'
      path: '/ai'
      fullPath: '/ai'
      preLoaderRoute: typeof AiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/announcements': {
      id: '/announcements'
      path: '/announcements'
      fullPath: '/announcements'
      preLoaderRoute: typeof AnnouncementsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/books': {
      id: '/books'
      path: '/books'
      fullPath: '/books'
      preLoaderRoute: typeof BooksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/calendar': {
      id: '/calendar'
      path: '/calendar'
      fullPath: '/calendar'
      preLoaderRoute: typeof CalendarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/events': {
      id: '/events'
      path: '/events'
      fullPath: '/events'
      preLoaderRoute: typeof EventsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/exams': {
      id: '/exams'
      path: '/exams'
      fullPath: '/exams'
      preLoaderRoute: typeof ExamsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/grades': {
      id: '/grades'
      path: '/grades'
      fullPath: '/grades'
      preLoaderRoute: typeof GradesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/groups': {
      id: '/groups'
      path: '/groups'
      fullPath: '/groups'
      preLoaderRoute: typeof GroupsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/homework': {
      id: '/homework'
      path: '/homework'
      fullPath: '/homework'
      preLoaderRoute: typeof HomeworkRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/messages': {
      id: '/messages'
      path: '/messages'
      fullPath: '/messages'
      preLoaderRoute: typeof MessagesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/news': {
      id: '/news'
      path: '/news'
      fullPath: '/news'
      preLoaderRoute: typeof NewsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy-policy': {
      id: '/privacy-policy'
      path: '/privacy-policy'
      fullPath: '/privacy-policy'
      preLoaderRoute: typeof PrivacyPolicyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/schedule': {
      id: '/schedule'
      path: '/schedule'
      fullPath: '/schedule'
      preLoaderRoute: typeof ScheduleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/search': {
      id: '/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/teachers': {
      id: '/teachers'
      path: '/teachers'
      fullPath: '/teachers'
      preLoaderRoute: typeof TeachersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tools': {
      id: '/tools'
      path: '/tools'
      fullPath: '/tools'
      preLoaderRoute: typeof ToolsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/videos': {
      id: '/videos'
      path: '/videos'
      fullPath: '/videos'
      preLoaderRoute: typeof VideosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/agent': {
      id: '/api/agent'
      path: '/api/agent'
      fullPath: '/api/agent'
      preLoaderRoute: typeof ApiAgentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/chat': {
      id: '/api/chat'
      path: '/api/chat'
      fullPath: '/api/chat'
      preLoaderRoute: typeof ApiChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/grade-text': {
      id: '/api/grade-text'
      path: '/api/grade-text'
      fullPath: '/api/grade-text'
      preLoaderRoute: typeof ApiGradeTextRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/reminders': {
      id: '/api/reminders'
      path: '/api/reminders'
      fullPath: '/api/reminders'
      preLoaderRoute: typeof ApiRemindersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dm/$userId': {
      id: '/dm/$userId'
      path: '/dm/$userId'
      fullPath: '/dm/$userId'
      preLoaderRoute: typeof DmUserIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/exams/$quizId': {
      id: '/exams/$quizId'
      path: '/$quizId'
      fullPath: '/exams/$quizId'
      preLoaderRoute: typeof ExamsQuizIdRouteImport
      parentRoute: typeof ExamsRoute
    }
    '/groups/': {
      id: '/groups/'
      path: '/'
      fullPath: '/groups/'
      preLoaderRoute: typeof GroupsIndexRouteImport
      parentRoute: typeof GroupsRoute
    }
    '/groups/$groupId': {
      id: '/groups/$groupId'
      path: '/$groupId'
      fullPath: '/groups/$groupId'
      preLoaderRoute: typeof GroupsGroupIdRouteImport
      parentRoute: typeof GroupsRoute
    }
    '/api/ai/actions': {
      id: '/api/ai/actions'
      path: '/api/ai/actions'
      fullPath: '/api/ai/actions'
      preLoaderRoute: typeof ApiAiActionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/ai/admin': {
      id: '/api/ai/admin'
      path: '/api/ai/admin'
      fullPath: '/api/ai/admin'
      preLoaderRoute: typeof ApiAiAdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/ai/conversations': {
      id: '/api/ai/conversations'
      path: '/api/ai/conversations'
      fullPath: '/api/ai/conversations'
      preLoaderRoute: typeof ApiAiConversationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/ai/report': {
      id: '/api/ai/report'
      path: '/api/ai/report'
      fullPath: '/api/ai/report'
      preLoaderRoute: typeof ApiAiReportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/ai/vision': {
      id: '/api/ai/vision'
      path: '/api/ai/vision'
      fullPath: '/api/ai/vision'
      preLoaderRoute: typeof ApiAiVisionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/books/': {
      id: '/api/books/'
      path: '/api/books'
      fullPath: '/api/books/'
      preLoaderRoute: typeof ApiBooksIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface ExamsRouteChildren {
  ExamsQuizIdRoute: typeof ExamsQuizIdRoute
}

const ExamsRouteChildren: ExamsRouteChildren = {
  ExamsQuizIdRoute: ExamsQuizIdRoute,
}

const ExamsRouteWithChildren = ExamsRoute._addFileChildren(ExamsRouteChildren)

interface GroupsRouteChildren {
  GroupsGroupIdRoute: typeof GroupsGroupIdRoute
  GroupsIndexRoute: typeof GroupsIndexRoute
}

const GroupsRouteChildren: GroupsRouteChildren = {
  GroupsGroupIdRoute: GroupsGroupIdRoute,
  GroupsIndexRoute: GroupsIndexRoute,
}

const GroupsRouteWithChildren =
  GroupsRoute._addFileChildren(GroupsRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  AiRoute: AiRoute,
  AnnouncementsRoute: AnnouncementsRoute,
  BooksRoute: BooksRoute,
  CalendarRoute: CalendarRoute,
  ContactRoute: ContactRoute,
  EventsRoute: EventsRoute,
  ExamsRoute: ExamsRouteWithChildren,
  GradesRoute: GradesRoute,
  GroupsRoute: GroupsRouteWithChildren,
  HomeworkRoute: HomeworkRoute,
  LoginRoute: LoginRoute,
  MessagesRoute: MessagesRoute,
  NewsRoute: NewsRoute,
  PrivacyPolicyRoute: PrivacyPolicyRoute,
  ProfileRoute: ProfileRoute,
  ScheduleRoute: ScheduleRoute,
  SearchRoute: SearchRoute,
  SettingsRoute: SettingsRoute,
  TeachersRoute: TeachersRoute,
  ToolsRoute: ToolsRoute,
  VideosRoute: VideosRoute,
  ApiAgentRoute: ApiAgentRoute,
  ApiChatRoute: ApiChatRoute,
  ApiGradeTextRoute: ApiGradeTextRoute,
  ApiRemindersRoute: ApiRemindersRoute,
  DmUserIdRoute: DmUserIdRoute,
  ApiAiActionsRoute: ApiAiActionsRoute,
  ApiAiAdminRoute: ApiAiAdminRoute,
  ApiAiConversationsRoute: ApiAiConversationsRoute,
  ApiAiReportRoute: ApiAiReportRoute,
  ApiAiVisionRoute: ApiAiVisionRoute,
  ApiBooksIndexRoute: ApiBooksIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
